### ISSUE TITLE
Concurrent calls warning when using this module

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/module-ballerinax-prometheus#146]
I've got the following warning when using this module. 

```
HINT [ballerinax/prometheus/0.2.0::metric_reporter.bal:(63:13,63:13)] concurrent calls will not be made to this method since the method is not an 'isolated' method
```

This seems to be a blocker for performance.

**Comment by NipunaMadhushan** [comment]
This issue occurs since the methods used in prometheus module (methods of `ballerina/observe` modules) are not isolated.
We need to make them isolated.
