### ISSUE TITLE
Use Testerina based testing instead of Java unit testing approach

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/module-ballerinax-prometheus#28]
**Description:**
Currently coverage numbers are not properly getting captures due to ballerina sources are being testing using Java unit tests. Proper approach is to migrate tests using Testerina and running using it.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by nadundesilva** [comment]
For these test cases we need support to change the configurations for each test case which is currently not supported (Spec Issue ballerina-platform/ballerina-spec#762)

**Comment by NipunaMadhushan** [comment]
This issue is not valid since we need to run Ballerina tests against a Ballerina application.
